### ISSUE TITLE
Already existing: Hybrids

### ISSUE THREAD

**Issue by tunnckoCore** [sonnyp/polygoat#5]
Hi. I wanted this thing before 2 years or so. So I created https://github.com/hybridables/hybridify and called all of them Hybrids, so @hybridables org was created. Last year I spent a lot of time on minimizing and minimizing and decoupling the things - so the smallest thing is `relike`. The master as you see it now isn't the `1.0.9` version which is too old. I'm just working on another underling libs.

Checkout these:
- [relike](https://github.com/hybridables/relike) - kinda "promisify", but no so, because it can be used to create promisify functions/libs. Its signature is `relike(fn, ..args)` which args will be passed to the fn, and returns promise. It also handles "promisify"-ing sync functions out of the box.
- [letta](https://github.com/hybridables/letta) - built on top of `relike`, but it can also accept generator functions. Also handles the `uncaughtException` and `unhandledRejection` events, which `relike` not doing, so using `relike` apps would crash directly on errors like `ENOENT` for example. It also pass all the `co@4` tests, of course integrated for the `relike`s signature.
- [handle-callback](https://github.com/hybridables/handle-callback), [then-callback](https://github.com/hybridables/then-callback), [handle-arguments](https://github.com/hybridables/handle-arguments) and [is-async-function](https://github.com/tunnckoCore/is-async-function) are ones in the absolute core. Mainly `is-async-function` and `is-callback-function` allows us to do all of this crazy things and libs.
- [native-promise](https://github.com/tunnckocore/native-promise) - Get native `Promise` or falsey value if not available.
- [native-or-another](https://github.com/tunnckoCore/native-or-another) - Always will expose native Promise if available, otherwise Bluebird **but only if you don't give another promise** module like q or promise or what you want.

There are tons of tests on all of the hybrids, tons of cases handled. Ton of work was done and a lot of experience was learned. I'm almost to the final line. Most of my work and these ~250 packages is because of the hybrid idea.

Because of the hybrids all of the [always-*](https://github.com/hybridables?utf8=%E2%9C%93&query=always) was born. They are more real "promisify" providing you different signatures. Most of them are a bit outdated currently, but they works.

**edit:** Why all of them? Because we need different signatures for different scenarios. Why not just a `fn.length` to check if function is async or not? Because it's not so easy. It is error prone and have bugs. The `is-async-function` is just an awesome peace of code.

All of them work on 0.10, defaulting to Bluebird promise or another that you can choose. But also all of them work totally with **native promise** and **always-first** tries to use it if exists.

Cheers. :star2:

**Comment by sonnyp** [comment]
@hybridables looks nice but polygoat is different and covers a specific use case.

polygoat 
- is 25 locs
- fast as plain callback/promise
- doesn't read `arguments`
- doesn't require Promise support/polyfill
- works in Node.js and in the browser without browserify/webpack/...
- doesn't do much and leaves details to the user 

Plus 

> polygoat is not so much about turning a callback function into a promise function, it's about designing an API/library that supports both.

although I don't think I made that clear enough as people keep comparing polygoat to promisify/thenify libraries.

**Comment by sonnyp** [comment]
@tunnckoCore I'll be interested to hear your opinion on https://github.com/sonnyp/polygoat/pull/2
